### PR TITLE
OA-Streams: Introduction of Cluster's Size

### PR DESCRIPTION
**Pull request by steveyuwono**
## Checklists:

- [ ] Read the [CONTRIBUTION](https://github.com/fhswf/MLPro/blob/master/CONTRIBUTING.md) guide (**required**).
- [ ] Update the history on the source code (**required**).

### CODE REVIEW

**Review by detlefarend — COMMENTED** [review]
Hi @steveyuwono, I just took a look at your extensions. It looks good and should perfectly solve the problem. I just have a hint about using the MLPro properties. These have four different attributes:



These are actually Python properties, which means they can be accessed as public attributes but implicitly call get/set methods.

To access the **value** of new MLPro property 'size' as intended you can say



instead of



There is actually just one reason for using the public method set: if you want to provide an explicit timestamp.

**Comment by steveyuwono** [comment]
> Hi @steveyuwono, I just took a look at your extensions. It looks good and should perfectly solve the problem. I just have a hint about using the MLPro properties. These have four different attributes:
> 
> 
> 
> These, in turn, are Python properties, which means they can be accessed as public attributes but implicitly call get/set methods.
> 
> To access the **value** of new MLPro property 'size' as intended you can say
> 
> 
> 
> instead of
> 
> 
> 
> There is actually just one reason for using the public method set: if you want to provide an explicit timestamp.

Hi Detlef, thank you for your review. Ahh sorry, we have discussed this but I forgot. It has now been updated accordingly.

**Comment by detlefarend** [comment]
@steveyuwono could you please extend the howtos by printing the sizes of the clusters at the end?

**Comment by steveyuwono** [comment]
> @steveyuwono could you please also extend the oa howtos by printing the sizes of the clusters at the end?

I have done it in howto_oa_wr 001 to 005. Do all howto_oa_ca_* also need this extension?

**Comment by detlefarend** [comment]
> > @steveyuwono could you please also extend the oa howtos by printing the sizes of the clusters at the end?
> 
> I have done it in howto_oa_wr 001 to 005. Do all howto_oa_ca_* also need this extension?

Hi Steve, yes please. Thank you!

**Pull request merged**
